---

kind: Component

patches:
  - patch: |-
      ---
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: logstash-dp
      spec:
        template:
          spec:
            volumes:
              - name: logstash-certs
                secret:
                  secretName: logstash-certs
            containers:
              - name: logstash
                volumeMounts:
                  - name: logstash-certs
                    mountPath: /usr/share/logstash/certs/
